### PR TITLE
Set max bar width for BarChart #406

### PR DESCRIPTION
**Pull request by Akuukis**
Set max bar width for BarChart #406

### CODE REVIEW

**Comment by yagebu** [comment]
A screenshot of what this looks like compared to before would be helpful

**Comment by Akuukis** [comment]
Before width of bars was stretched unlimited. Even if there was only 1 bar, it was stretched A LOT.
[](https://postimg.org/image/5o5r9gxcz/)
Now max width is capped.
[](https://postimg.org/image/8fuctxkb3/)

P.S. Preview on my 1366p wide screen.

**Comment by yagebu** [comment]
I think it looks quite lopsided and I prefer the symmetry of the current solution. How about https://github.com/yagebu/fava/commit/7f1ad73ac0ee4cd86a7d71c26e755333f0634c5f? Keeping the columns inplace but limit their width.

screenshot

**Comment by xentac** [comment]
+1 for keeping the symmetry.

**Comment by Akuukis** [comment]
+1 for symmetry, but I personally dislike big gaps between them. Maybe keep [akuukis@2031451](https://github.com/beancount/fava/pull/528/commits/20314513e4d67945a5650fb38b8c3a2b2751ea0d) but center the graph itself?

**Comment by aumayr** [comment]
I'm also for @Akuukis's solution, but centered.

**Comment by yagebu** [comment]
I prefer the gaps but I'm fine either way. Can you update this PR @Akuukis?

**Comment by Akuukis** [comment]
Here's screenshot of centered BarChart as in last commit
[](https://postimg.org/image/r70ok37hv/)

**Comment by aumayr** [comment]
I really like how this looks - thanks @Akuukis!

Before we merge there are some lint-errors (see https://travis-ci.org/beancount/fava/jobs/223853140) - run `make lint` to check for yourself.

**Comment by Akuukis** [comment]
Fixed all `npm lint` errors.

**Pull request merged**
