### PR TITLE
Update development.rst: Add extra commands

### PR DESCRIPTION
**Pull request by mhansen**
These were some commands that I had to google how to install.

### CODE REVIEW

**Comment by yagebu** [comment]
It already says that these tools are required above the code block and I'd rather keep it that way, since for most users it is probably preferable to install those tools with their platform package manager instead of pip.

**Comment by mhansen** [comment]
I wasn’t sure which package manager they’d be (had to google it, at first I
thought they’d be npm, and some of the names like “tox” were hard to google
with irrelevant results coming up).

 I thought if we’re using virtual envs and these are python modules we
would prefer to use the venv over the OS package manager, in case other
programs need other versions? And the OS package managers are often out of
date? I’m not very familiar with norms on python projects though.

At any rate I’d like to make it a bit clearer how to install these deps.

**Comment by yagebu** [comment]
Thanks for the feedback. I'll try to expand the paragraph before the code block a bit to explain how these tools can be installed and link to their homepages so that it's clear which tools are meant. tox and pre-commit are both rather compatible since they're both just script runners, so installing from package managers is fine (and should ensure that you don't have an outdated version in your venv a year from now).

**Comment by mhansen** [comment]
Thanks, sounds good! By the way, once I got these tools set up, it was a
nice development experience with quick reload to see the changes, cheers.

**Comment by mhansen** [comment]
Thanks! Looks good

**Pull request closed without merging**
