### PR TITLE
remove unused args from extension

### PR DESCRIPTION
**Pull request by redstreet**

### CODE REVIEW

**Comment by redstreet** [comment]
@seltzered: any objections?

**Comment by seltzered** [comment]
I think the original intent was to handle Time filtering since nearly all standard views in Fava seem support Time Filtering. Feel like this is more of a bug/incomplete feature since I never passed the time arguments in.

**Comment by redstreet** [comment]
Makes sense. Are you okay with cleaning it up for now to minimize confusion? You can add time filtering in the future.

**Comment by seltzered** [comment]
Fine with removing it for now, let's create another issue so we don't forget to add it later.

**Comment by redstreet** [comment]
Sounds good. I'll let you create the issue if that's cool, since you have a better sense of what you'd like added :).

@yagebu good to merge.

**Pull request merged**
