### PR TITLE
add extension hook after entry modification

### PR DESCRIPTION
**Pull request by xinluh**
There are hooks currently when new entry are inserted, file is saved, or metadata is added, but no hook when an entry is modified in the context popup.

### CODE REVIEW

**Comment by yagebu** [comment]
Thanks for the PR, looks like a good addition :) This currently fails the CI, could you fix that?

**Comment by xinluh** [comment]
@yagebu done

**Comment by yagebu** [comment]
> done (debian build failure seems unrelated)

The debian failure is fixed in master so a merge or rebase would have fixed that as well.

**Comment by yagebu** [comment]
I've merged this and clarified the types for the extension hooks (this one is called with the entry as a string, whereas the others are called with a Beancount entry)

**Pull request closed without merging**
