### PR TITLE
Initial attempt at documenting my fava+oauth2_proxy+letsencrypt setup

### PR DESCRIPTION
**Pull request by xentac**
I'm sure there are minor mistakes, but hopefully there are no major ones.

### CODE REVIEW

**Comment by aumayr** [comment]
I think I can contribute a bit as well by

- a `docker-compose.yml`-file to make deployment easier and
- using `https://github.com/SteveLTN/https-portal/` to cut down the number of containers needed for Let's Encrypt

@xentac What do you think about those "changes"?

**Comment by xentac** [comment]
Both of these things I chose not to do to make the system more flexible and
secure. I don't use docker-compose so that I can start my containers as
systemd services and run other web services on the same machine. I chose
the 3 container solution for letsencrypt to keep the docker socket out of a
container that is publicly accessible. The nginx container exists only to
serve web traffic, not to do any management.

I'm not opposed to these changes, I just can't test them. Perhaps we could
offer both solutions?

**Comment by xentac** [comment]
Who is responsible for merging this one?

**Comment by aumayr** [comment]
Thanks again, @xentac!

**Pull request merged**
