### PR TITLE
Entry editor

### PR DESCRIPTION
**Pull request by yagebu**
- Use file hash to check that edited file is not changed externally.
- Replace the context overlay with an editor for the lines of the entry.

Ref #534; Somewhat related to #456.

### CODE REVIEW

**Comment by aumayr** [comment]
Looks awesome and works as advertised! And makes a huge difference in my workflow, as I very often go to a specific transaction in the editor through the Context page. 

One question about UX: Should a successfull "Save" close the overlay?

**Comment by yagebu** [comment]
> One question about UX: Should a successfull "Save" close the overlay?

Yes that is the plan, will go together with some reworking of the overlay-closing logic.

**Comment by aumayr** [comment]
Bug: The z-index of the account-suggestion-overlay when typing in the inline-editor is behind the context-overlay.

**Comment by aumayr** [comment]
Let's bake a new release?

**Comment by yagebu** [comment]
Sounds good - although I would give it a few days to see if some bugs turn up. I pushed new translateable strings to POEditor and notified the contributors there - let's also give them a few days ;)

**Comment by aumayr** [comment]
> Sounds good - although I would give it a few days to see if some bugs turn up.

I did use this feature somewhat in the last week, and no big issues on my side.

**Pull request merged**
