### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by toddy15**
Hi,

I've updated and completed the German translation. Unfortunately, I cannot commit this at poeditor.com, so I've created a PR. If this needs to go via poeditor, please give me a hint how to upload the changes there.

Regards,
Tobias

### CODE REVIEW

**Comment by yagebu** [comment]
Danke Tobias :)

> Unfortunately, I cannot commit this at poeditor.com

I'm not really sure how it works for new contributors, I thought you could somehow ask to be a new contributor there? In any case, I've added you on poeditor - could you add the translations there?

**Comment by toddy15** [comment]
Hi,

thanks for adding me at poeditor -- I could not find an option at that website to ask for access to fava. However, now it worked, the translations are committed to poeditor. Are those fetched automatically into the git repository?

Regards,
Tobias

**Comment by yagebu** [comment]
> Are those fetched automatically into the git repository?

There's a script to download them that I run every once in a while and before every release - will do that now.

**Comment by xuhcc** [comment]
Hi @yagebu !
I would like to contribute translation as well. But the link in [CONTRIBUTING.md](https://github.com/beancount/fava/blob/master/CONTRIBUTING.md#contributing-translations) leads me to "404 error" page.

**Pull request closed without merging**
