### PR TITLE
Add credentials: 'include' to all fetch calls

### PR DESCRIPTION
**Pull request by xentac**
Fixes https://github.com/beancount/fava/issues/388.

### CODE REVIEW

**Comment by aumayr** [comment]
Thanks @xentac!

**Comment by yagebu** [comment]
Would be nicer to handle this in one place...

**Comment by yagebu** [comment]
A helper function simply called `fetch` in `helpers.js` would be best IMHO. Also, it should set `credential: 'same-origin'`. I'll revert this PR, @xentac could you provide a PR updated with my suggestions?

**Comment by xentac** [comment]
Yeah, I'll write one when I get a chance.

**Pull request merged**
