### PR TITLE
add tree view for source files in editor.

### PR DESCRIPTION
**Pull request by xiaoniu-578fa6bff964d005**
Implement #1136 .

Some Previews:
s1
s2

Some possible improvements:
1. Tweak the style.
2. Decide whether we still want `sources` and `list_sources`.

### CODE REVIEW

**Comment by yagebu** [comment]
Hi @xiaoniu-578fa6bff964d005, thanks for the PR :)

I'm not willing to merge such a substantial change without any tests and I'm somewhat hesitant to merge such a big change for this feature at all. Could this maybe be implemented more succinctly by not rendering a full tree, but rather by just splitting the path into directory and filename and then just grouping by directory? I think that would already vastly reduce the visual clutter.

**Comment by xiaoniu-578fa6bff964d005** [comment]
Do you have any example of "splitting the path into directory and filename and then just grouping by directory"?

**Comment by yagebu** [comment]
> Do you have any example of "splitting the path into directory and filename and then just grouping by directory"?

Well, it would look like your example image, but instead of having a tree of directories it would just be a list of directories and under each directory the files in that directory would be listed.

**Comment by xiaoniu-578fa6bff964d005** [comment]
Does

> 
> 
> > Do you have any example of "splitting the path into directory and filename and then just grouping by directory"?
> 
> Well, it would look like your example image, but instead of having a tree of directories it would just be a list of directories and under each directory the files in that directory would be listed.

Does each directorey have the full path? Do we need to handle nested folders?

**Comment by yagebu** [comment]
Hey @xiaoniu-578fa6bff964d005, sorry for the long silence, I was on vacation and somewhat forgot about this.

>  Does each directorey show the full path? Do we need to handle nested folders?

I don't really have a strong opinion on this. I guess ignoring nested folders and showing the full path would be "good enough" without having to add about 150 lines of code.

If you really want to implement this as a tree view, it should be done completely in the frontend. The `stratify` function in `frontend/src/lib/tree` could be used to generate the tree from the array of source files (it would have to be slightly modified to obtain the "parent" for a file path instead of an account path).

**Comment by yagebu** [comment]
I'm closing this stale PR. If you want to continue to work on this, feel free to reopen

**Comment by xiaoniu-578fa6bff964d005** [comment]
Sorry for the absence for almost one year.
During this time, have we introduced any other way to alleviate the problem that the file list is difficult to read when there are a large number of files?
In the past year I was using my implementation in the PR. Recently I wish to merge the upstream but it appears to be hard as many refactor has happened.
If there is any "good enough" design, I think I will just abandon the tree view in this PR and adopt design in the official repository.

**Pull request closed without merging**
