### PR TITLE
Add a note about building frontend code.

### PR DESCRIPTION
**Pull request by umangv**
Right now, following the instructions as-is leaves you with a flask server that runs but doesn't have the static files necessary to actually do anything useful.

### CODE REVIEW

**Comment by yagebu** [comment]
The explicit build step should not be necessary actually. `_build_backend.py` which is used as the Python package build backend calls `npm install` and `npm run build` unless the app.js is newer than all frontend source files. How did you install Fava since that doesn't seem to have worked in your case?

**Comment by yagebu** [comment]
I guess this might be due to a build frontend calling build_wheel directly - I'll add the build_wheel hook to `_build_backend.py`, see #1771

**Comment by umangv** [comment]
Hmm, I'm not sure that worked for me:

```sh
$ mkdir /tmp/fava_build
$ cd /tmp/fava_build/
$ git clone https://github.com/beancount/fava.git
Cloning into 'fava'...
# ...
Resolving deltas: 100% (21142/21142), done.
$ cd fava/
$ python3 -m venv venv
$ . venv/bin/activate
$ which pip
/tmp/fava_build/fava/venv/bin/pip
$ pip install pre-commit
# [...]
Successfully installed cfgv-3.4.0 distlib-0.3.8 filelock-3.13.1 identify-2.5.35 nodeenv-1.8.0 platformdirs-4.2.0 pre-commit-3.6.2 pyyaml-6.0.1 virtualenv-20.25.1
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
$ pip install --editable .
Obtaining file:///tmp/fava_build/fava
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
# [...]
Building wheels for collected packages: fava
  Building editable for fava (pyproject.toml) ... done
  Created wheel for fava: filename=fava-1.27.4.dev1+gad224193-0.editable-py3-none-any.whl size=4335 sha256=cc0bb0e2e9feba17c4d583871ee9acbd89f7c2012e69fd1111f5cc6c7c63f7f6
  Stored in directory: /tmp/pip-ephem-wheel-cache-bgvfq213/wheels/44/a2/71/f4fb75b5607ac69463b9b8e9f67d14a1ea6e9708e80fef5776
Successfully built fava
Installing collected packages: pytz, ply, bottle, urllib3, uritemplate, tomli, soupsieve, six, simplejson, python-magic, pyparsing, pyasn1, protobuf, pluggy, packaging, more-itertools, MarkupSafe, markdown2, lxml, itsdangerous, iniconfig, idna, exceptiongroup, click, charset-normalizer, chardet, certifi, cachetools, blinker, Babel, Werkzeug, rsa, requests, python-dateutil, pytest, pyasn1-modules, pdfminer2, Jinja2, jaraco.functools, httplib2, googleapis-common-protos, beautifulsoup4, google-auth, Flask, cheroot, google-auth-httplib2, google-api-core, Flask-Babel, google-api-python-client, beancount, fava
Successfully installed Babel-2.14.0 Flask-3.0.2 Flask-Babel-4.0.0 Jinja2-3.1.3 MarkupSafe-2.1.5 Werkzeug-3.0.1 beancount-2.3.6 beautifulsoup4-4.12.3 blinker-1.7.0 bottle-0.12.25 cachetools-5.3.3 certifi-2024.2.2 chardet-5.2.0 charset-normalizer-3.3.2 cheroot-10.0.0 click-8.1.7 exceptiongroup-1.2.0 fava-1.27.4.dev1+gad224193 google-api-core-2.17.1 google-api-python-client-2.121.0 google-auth-2.28.2 google-auth-httplib2-0.2.0 googleapis-common-protos-1.63.0 httplib2-0.22.0 idna-3.6 iniconfig-2.0.0 itsdangerous-2.1.2 jaraco.functools-4.0.0 lxml-5.1.0 markdown2-2.4.13 more-itertools-10.2.0 packaging-24.0 pdfminer2-20151206 pluggy-1.4.0 ply-3.11 protobuf-4.25.3 pyasn1-0.5.1 pyasn1-modules-0.3.0 pyparsing-3.1.2 pytest-8.1.1 python-dateutil-2.9.0.post0 python-magic-0.4.27 pytz-2024.1 requests-2.31.0 rsa-4.9 simplejson-3.19.2 six-1.16.0 soupsieve-2.5 tomli-2.0.1 uritemplate-4.1.1 urllib3-2.2.1
$ fava $MYBEANCOUNT 
Starting Fava on http://127.0.0.1:5000
```
In a separate terminal...
```sh
$ curl http://127.0.0.1:5000/static/app.js
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
$ pwd
/tmp/fava_build/fava
$ git log --format=oneline | head -n 5
ad224193eecd69d15a0192d9bfb8da4e673709bc test: extract helpers in frontend tests
539719be5e70188ee8e0d0c96c19c589c9ea9bed _build_backend: add build_wheel
394162941a1e431523e5f22981ef9ddcefc8dfea deps
05097901d78257a6f46f64968ca173d4afd9beb1 ci,tox: use tox-uv; use package = wheel
d8237e1bebbccd40193731d36b8284512a5a2874 deps
```
The last part confirms that I do have #1771 (i.e., commit 539719b)

**Comment by yagebu** [comment]
Thanks for trying again (I had only checked a standard wheel build) - it seems there is a separate build hook for editable wheels nowadays. So #1775 should fix this (which also adds a test to make sure we've got all hooks covered).

**Comment by umangv** [comment]
Thanks @yagebu! #1775 seems to have fixed it. I started afresh and repeated the steps in my previous comment and the frontend got compiled and included in the build.

**Pull request closed without merging**
