### PR TITLE
Conversion to a single currency

### PR DESCRIPTION
**Pull request by yagebu**
Ref #242

### CODE REVIEW

**Comment by aumayr** [comment]
👍🏻

**Comment by xentac** [comment]
This isn't working quite the way I thought it would...

Most charts keep displaying only my operating currencies... though choosing to convert to one of them seems to work ok.

If I'm looking at an expense account that has both USD and CAD transactions, the Account Balance graph doesn't change, the Changes graph changes (only if I select one of the two operating curriences), but the Changes graphs doesn't change if I choose a non-operating currency.

None of the transactions are converted when displayed in the journal, so they always show their original currency.

I also see some weird entries in the Converted to dropdown.  Specifically I'm seeing some things listed that aren't commodities.  A handful of transactions I add document metadata to, representing an identifier from a pdf.  Those values also show up in the dropdown...

Shall I file bugs for these or do you have easy fixes for them?  I may be able to work on some of them, but it'll be slowly over the next few weeks.

**Comment by aumayr** [comment]
> Shall I file bugs for these or do you have easy fixes for them? I may be able to work on some of them, but it'll be slowly over the next few weeks.

@xentac Yes please do file bugs if you find some! If you start working on them please assign yourself to them in the Github issue, so there is no double-work.

**Comment by yagebu** [comment]
Thanks for the feedback @xentac!

> Most charts keep displaying only my operating currencies... though choosing to convert to one of them seems to work ok.

The bar charts currently only display operating currencies, I guess if one converts to another currency that should also be displayed.

> If I'm looking at an expense account that has both USD and CAD transactions, the Account Balance graph doesn't change, the Changes graph changes (only if I select one of the two operating curriences), but the Changes graphs doesn't change if I choose a non-operating currency

Currently the conversion only applies to amounts that are normally displayed at cost. I do agree that when selecting "convert" one would probably expect that the account balance in the chart and the account journal is also converted. This would introduce the following (probably acceptable) inconsistency: When "At Cost" is selected, the units of the account balance are shown so the option doesn't seem to apply but with, say, "Converted to USD" it *would* apply. 

>None of the transactions are converted when displayed in the journal, so they always show their original currency.

As the journal is just a fancy rendering of the input file, the numbers there shouldn't be converted IMHO. In the account journal however the above applies to the change and balance columns.

> I also see some weird entries in the Converted to dropdown. Specifically I'm seeing some things listed that aren't commodities. A handful of transactions I add document metadata to, representing an identifier from a pdf. Those values also show up in the dropdown...

This is either a problem with your input or Beancount. What kind of entries make these unexpected currencies show up?

**Comment by xentac** [comment]
> This is either a problem with your input or Beancount. What kind of entries make these unexpected currencies show up?

It's sort of easy to find the exact transaction because there is a single reference to the "currencies" in my file.

```
2015-01-29 * "S04128836C"
  document: RSUA148148
  Assets:US:Schwab:HOOL 3 HOOL {9 USD}
  Income:US:Hooli:RSU -45.00 USD
  Assets:Hooli:RSURefund
  Expenses:Taxes:TY2015:US:Medicare 5.00 USD
  Expenses:Taxes:TY2015:US:Federal 6.00 USD
  Expenses:Taxes:TY2015:US:SocSec 4.00 USD
```

This is a simplified transaction that probably also has the problem.

**Comment by yagebu** [comment]
Strings need to be quoted.

**Comment by xentac** [comment]
Ha! Thanks for that.

**Comment by xentac** [comment]
> Currently the conversion only applies to amounts that are normally displayed at cost. I do agree that when selecting "convert" one would probably expect that the account balance in the chart and the account journal is also converted. This would introduce the following (probably acceptable) inconsistency: When "At Cost" is selected, the units of the account balance are shown so the option doesn't seem to apply but with, say, "Converted to USD" it would apply.

I'm not sure I understand what you mean by "the units of the account balance are shown".  Don't the graphs and balances always show units?

> As the journal is just a fancy rendering of the input file, the numbers there shouldn't be converted IMHO. In the account journal however the above applies to the change and balance columns.

I was talking about the Balance and Change columns.  I agree that the detailed journal rows should be untouched.

**Pull request merged**
