### PR TITLE
update zh

### PR DESCRIPTION
**Pull request by dallaslu**

### CODE REVIEW

**Comment by yagebu** [comment]
Hey, thanks for working on the translations - however we work on the translations on poeditor.com: https://poeditor.com/join/project/TlraSxOCxt

Could you sign up and add your translations there instead?

**Comment by dallaslu** [comment]
> 
> 
> Hey, thanks for working on the translations - however we work on the translations on poeditor.com: https://poeditor.com/join/project/TlraSxOCxt
> 
> Could you sign up and add your translations there instead?

The page shows: Chinese(Pending)

**Comment by sincerefly** [comment]
Pending

image

**Comment by yagebu** [comment]
Done, I've added you

**Pull request closed without merging**
