### PR TITLE
Add Ukrainian translations

### PR DESCRIPTION
**Pull request by Argentumbolo**
- Add translations text.
  - Add compiled (by poedit) binary file.
  - Update languages lists in sources.
  - Update documentation.

### CODE REVIEW

**Comment by Argentumbolo** [comment]
I tried to add it by POEditor.com but Ukrainial language request steel have `pending` status.
So this pull request just for example if POEdit will allow translation or for merge if don't.

**Comment by aumayr** [comment]
Thanks for providing the translation! I also accepted your request on POEditor.com (sorry for the late response).

**Comment by yagebu** [comment]
Mhh this shouldn't have been merged - will just create noise when we properly download the translations

**Comment by aumayr** [comment]
Oh, sorry… didn't think that this might cause troubles when merging the translations.

**Comment by yagebu** [comment]
It's actually not a big deal, sorry if I made it sound like one :)

I just looked on POEditor - the slovak translations also seems new, right?

**Comment by aumayr** [comment]
> I just looked on POEditor - the slovak translations also seems new, right?

Yes - I did approve the contributer a couple of days (weeks?) ago.

**Comment by yagebu** [comment]
Do you get an email notification for these new contributor requests?

**Comment by aumayr** [comment]
Yes, for both of them (Slovak on 13th of March)

**Comment by yagebu** [comment]
I've added slovak to the list of translations too (and updated all the files)

Thank you for the translations @Argentumbolo!

**Comment by Argentumbolo** [comment]
Thanks for merge and approve @aumayr @yagebu

But I stell don't understand how to work woth POEditor (and I think that CrowdIn much better for this).
Should I import exist file in POEditor editor for work with it in the future, or it'll be pulled there automaticly from repository?
Because I'm afraid that I could do some conflictes.

**Comment by yagebu** [comment]
> Should I import exist file in POEditor editor for work with it in the future, or it'll be pulled there automaticly from repository?
Because I'm afraid that I could do some conflictes.

@Argentumbolo: I've imported your translations from this PR on POEditor just now. All changes should be done on poeditor (and will be imported into Fava from time to time)

> But I stell don't understand how to work woth POEditor (and I think that CrowdIn much better for this).

What's wrong with poeditor, or what are the big advantages of crowdin?

**Comment by Argentumbolo** [comment]
> I've imported your translations from this PR on POEditor just now

OK, I got it.

> or what are the big advantages of crowdin?

Because in crowdin I can see: phrase _context_, comments of other translators, suggestions from automatic services, translations of this phrase on other languages which I know.
screenshot-2018-3-26 base locale - gogs - crowdin translation

> What's wrong with poeditor

From my point of view It's have the same features as poedit.
So it's very ascetic tool. (But it have _import_ option, so it's not a problem)

**Pull request merged**
