### PR TITLE
WIP: Basic scroll to top/bottom buttons

### PR DESCRIPTION
**Pull request by alexiri**
I took another look at the code in hopes of implementing #811 and I realized it was easier than I thought. I still can't get the buttons aligned to the right, though, so hopefully somebody with more CSS knowledge can give me a hand.

### CODE REVIEW

**Comment by yagebu** [comment]
Why not have them align to the left like the rest of the controls? Does that look bad?

**Comment by alexiri** [comment]
It doesn't look great aligned left because the rest of the controls are menu items and these two are more like buttons. I'll leave it up to you, though.

**Comment by yagebu** [comment]
The buttons look somewhat slanted. Also, the svgs seem excessively large considering it's just a bunch of triangles

**Comment by alexiri** [comment]
I basically stole the SVGs from Gitlab. Can you suggest better icons?

**Comment by yagebu** [comment]
> I basically stole the SVGs from Gitlab. Can you suggest better icons?

Make them yourself? I don't know, really... This doesn't have any priority me for though, so if you can replace the SVG with some better looking ones that we can actually use, I'd be willing to merge this, otherwise, not so much.

**Comment by xentac** [comment]
Check out some open source icon sets (for example https://useiconic.com/open).
You'll still want them to fit with the overall beancount style though.

**Comment by yagebu** [comment]
Closing this due to inactivity

**Pull request closed without merging**
