### PR TITLE
[Feature]: Support nested price conversion

### PR DESCRIPTION
**Pull request by fengkx**
Support nested price conversion Related issue #1407 

Always convert to biggest value using Bellman–Ford algorithm.

For example, when using **convert to HKD**, find the shortest(Smallest Conversion Rate) from HKD to others currency. $K$
then the price from others to HKD is $\frac{1}{K}$ (largest)

- [x] Unit test, linter
- [x] Description, comment

### CODE REVIEW

**Comment by yagebu** [comment]
Hi, thank you for the PR.

To allow for multiple currency conversions, I prefer a more explicit approach where one either explicitly adds additional prices via a plugin (as is already possible) or by explicitly specifying the currencies to convert via/to. With #1732 the latter will also be possible. Also, the implementation here does not seem very performant, on some reports the load times seem to have doubled. So I do not intend to merge your PR - does #1732 also work for your use case?

**Comment by fengkx** [comment]
I use the master branch, But can't find the correct way to use #1732.
image

I have a long list of price directive created by bean-price daily. I want all Other currency be converted into CNY when I choose converted to CNY.

**Comment by yagebu** [comment]
If you have conversion rates from your other currencies to, e.g., HKD (and then prices for HKD in CNY), you could choose HKD,CNY as conversions to get everything converted to CNY.

**Comment by fengkx** [comment]
I am using the main branch, But I can't find the option in the UI.
image

What if I have many other currenecies (or stocks) which also want to convert to CNY?

**Comment by yagebu** [comment]
> I am using the main branch, But I can't find the option in the UI.

You can select multiple currencies from that dropdown

**Comment by fengkx** [comment]
OK, I understand it now. The order in which I select affects the conversion. My pr uses the Bellman–Ford algorithm to find the shortest path, which makes it slow, while the current solution requires the user to find the correct path. I think the UI does not inform the user that the selection order would affect the results.

**Comment by yagebu** [comment]
> OK, I understand it now. The order in which I select affects the conversion. My pr uses the Bellman–Ford algorithm to find the shortest path, which makes it slow, while the current solution requires the user to find the correct path. 

Exactly - it also allows/requires the user to pick a specific path. Finding shouldn't normally be hard AFAIKT, since it will usually be just via your operating currencies.

>I think the UI does not inform the user that the selection order would affect the results.

That's why I added a help page to describe it - I don't think this can be easily shown in the UI

> I have a question while I am devloping locally. How to set up the translations... It seems to require a POEDITOR_TOKEN

No, that token is only necessary to update the translations from poeditor.com (where they are edited). If you want to edit the translations, you'll have to do so at poeditor.

**Pull request closed without merging**
